import { SiteContent } from '@/types/content'

// This file is auto-generated from content.yaml
// Do not edit this file directly - edit content.yaml instead

const contentData: SiteContent = {
  "personal": {
    "name": "Praba Siva",
    "title": "Chief Strategist, Architect & Engineer",
    "tagline": "Creative Problem Solver",
    "email": "mail@prabasiva.com",
    "location": "Ohio, USA",
    "bio": "Passionate about building transformational business models & process to drive bottom and top lines. Specializing in Agentic AI development and deployment"
  },
  "social": {
    "github": "https://github.com/prabasiva",
    "linkedin": "https://linkedin.com/in/prabasiva",
    "twitter": "https://x.com/prabasiva",
    "website": "https://blog2.prabasiva.com"
  },
  "navigation": [
    {
      "name": "Home",
      "href": "#home"
    },
    {
      "name": "Experience",
      "href": "#experience"
    },
    {
      "name": "Projects",
      "href": "#projects"
    },
    {
      "name": "About",
      "href": "#about"
    }
  ],
  "hero": {
    "greeting": "Hello, I'm",
    "subtitle": "Full Stack Developer & Creative Problem Solver",
    "description": "Passionate about building beautiful, functional web experiences. Specializing in React, Next.js, and modern web technologies.",
    "cta_text": "View My Work",
    "cta_link": "#experience"
  },
  "experience": [
    {
      "title": "Senior Full Stack Developer",
      "company": "Tech Company",
      "period": "2022 - Present",
      "description": "Led development of microservices architecture using Next.js and Node.js. Improved application performance by 40% through optimization strategies.",
      "technologies": [
        "React",
        "Next.js",
        "Node.js",
        "PostgreSQL",
        "AWS"
      ]
    },
    {
      "title": "Full Stack Developer",
      "company": "Startup Inc",
      "period": "2020 - 2022",
      "description": "Built and maintained e-commerce platform serving 100k+ users. Implemented real-time features using WebSockets and Redis.",
      "technologies": [
        "React",
        "Express",
        "MongoDB",
        "Redis",
        "Docker"
      ]
    },
    {
      "title": "Frontend Developer",
      "company": "Digital Agency",
      "period": "2018 - 2020",
      "description": "Developed responsive web applications for various clients. Collaborated with design team to implement pixel-perfect UI components.",
      "technologies": [
        "React",
        "Vue.js",
        "SASS",
        "Webpack",
        "Git"
      ]
    }
  ],
  "projects": [
    {
      "title": "E-Commerce Platform",
      "description": "Full-stack e-commerce solution with real-time inventory management, payment processing, and admin dashboard.",
      "image": "/placeholder-project1.jpg",
      "technologies": [
        "Next.js",
        "TypeScript",
        "Stripe",
        "PostgreSQL"
      ],
      "liveUrl": "https://example.com",
      "githubUrl": "https://github.com/yourusername/project1"
    },
    {
      "title": "Task Management App",
      "description": "Collaborative task management application with real-time updates, drag-and-drop functionality, and team features.",
      "image": "/placeholder-project2.jpg",
      "technologies": [
        "React",
        "Node.js",
        "Socket.io",
        "MongoDB"
      ],
      "liveUrl": "https://example.com",
      "githubUrl": "https://github.com/yourusername/project2"
    },
    {
      "title": "AI Content Generator",
      "description": "AI-powered content generation tool using OpenAI API for creating blog posts, social media content, and more.",
      "image": "/placeholder-project3.jpg",
      "technologies": [
        "Next.js",
        "OpenAI API",
        "Tailwind CSS",
        "Vercel"
      ],
      "liveUrl": "https://example.com",
      "githubUrl": "https://github.com/yourusername/project3"
    }
  ],
  "about": {
    "title": "About Me",
    "subtitle": "Who I Am",
    "bio": [
      "I'm a passionate full-stack developer with a love for creating elegant solutions to complex problems. With over 5 years of experience in web development, I've had the opportunity to work on diverse projects ranging from startups to enterprise applications.",
      "My journey in tech started with curiosity about how things work on the web, and it has evolved into a career focused on building meaningful digital experiences that make a difference.",
      "When I'm not coding, you can find me exploring new technologies, contributing to open-source projects, or sharing knowledge through technical writing and mentoring."
    ],
    "skills": [
      {
        "category": "Frontend",
        "items": [
          "React",
          "Next.js",
          "TypeScript",
          "Tailwind CSS",
          "Framer Motion"
        ]
      },
      {
        "category": "Backend",
        "items": [
          "Node.js",
          "Express",
          "PostgreSQL",
          "MongoDB",
          "REST APIs"
        ]
      },
      {
        "category": "Tools",
        "items": [
          "Git",
          "Docker",
          "AWS",
          "Vercel",
          "VS Code"
        ]
      }
    ],
    "highlights": [
      {
        "icon": "Code2",
        "title": "Clean Code",
        "description": "Writing maintainable, scalable, and well-documented code"
      },
      {
        "icon": "Palette",
        "title": "Design Focus",
        "description": "Creating beautiful and intuitive user interfaces"
      },
      {
        "icon": "Lightbulb",
        "title": "Problem Solving",
        "description": "Finding creative solutions to complex challenges"
      },
      {
        "icon": "Users",
        "title": "Collaboration",
        "description": "Working effectively in cross-functional teams"
      }
    ]
  },
  "footer": {
    "copyright": "All rights reserved.",
    "madeWith": "Made with ❤️ by"
  }
}

export function getContent(): SiteContent {
  return contentData
}