const fs = require('fs')
const path = require('path')
const yaml = require('js-yaml')

// Read YAML content
const yamlPath = path.join(process.cwd(), 'content.yaml')
const yamlContent = fs.readFileSync(yamlPath, 'utf8')
const content = yaml.load(yamlContent)

// Generate TypeScript content file
const tsContent = `import { SiteContent } from '@/types/content'

// This file is auto-generated from content.yaml
// Do not edit this file directly - edit content.yaml instead

const contentData: SiteContent = ${JSON.stringify(content, null, 2)}

export function getContent(): SiteContent {
  return contentData
}`

// Write the generated content
const outputPath = path.join(process.cwd(), 'lib', 'content.ts')
fs.writeFileSync(outputPath, tsContent)

console.log('✅ Generated content.ts from content.yaml')